using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.IO;
using System.Linq;



namespace ResourceLoader.Generator
{
    [Generator]
    public sealed class ResourceLoaderGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations = context
                .SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetClassWithResourceFolder(ctx))
                .Where(static c => c is not null)!;

            IncrementalValueProvider<string?> projectDir = context
                .AnalyzerConfigOptionsProvider
                .Select(static (provider, _) =>
                {
                    provider.GlobalOptions.TryGetValue("build_property.projectdir", out string? dir);
                    return dir;
                });

            IncrementalValuesProvider<(ClassDeclarationSyntax Class, string? ProjectDir)> combined =
                classDeclarations.Combine(projectDir);

            context.RegisterSourceOutput(combined, static (ctx, source) =>
                Execute(ctx, source.Item1, source.Item2));
        }

        private static ClassDeclarationSyntax? GetClassWithResourceFolder(GeneratorSyntaxContext ctx)
        {
            ClassDeclarationSyntax classDecl = (ClassDeclarationSyntax)ctx.Node;

            foreach (AttributeListSyntax attributeList in classDecl.AttributeLists)
            {
                foreach (AttributeSyntax attribute in attributeList.Attributes)
                {
                    if (ctx.SemanticModel.GetSymbolInfo(attribute).Symbol is not IMethodSymbol attributeSymbol)
                        continue;

                    string fullName = attributeSymbol.ContainingType.ToDisplayString();
                    if (fullName == "ResourceLoader.Attributes.ResourceFolderAttribute")
                        return classDecl;
                }
            }

            return null;
        }

        private static void Execute(
            SourceProductionContext ctx,
            ClassDeclarationSyntax classDecl,
            string? projectDir)
        {
            if (projectDir is null)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "RL0001",
                        "Could not determine project directory",
                        "ResourceLoader could not determine the project directory",
                        "ResourceLoader",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None));
                return;
            }

            // Get the ScanPath value from the attribute
            AttributeSyntax? attribute = classDecl.AttributeLists
                .SelectMany(al => al.Attributes)
                .FirstOrDefault(a => a.Name.ToString().Contains("ResourceFolder"));

            if (attribute?.ArgumentList?.Arguments.Count < 2)
                return;

            string scanPath = attribute!.ArgumentList!.Arguments[0]
                .Expression.ToString().Trim('"');
            string runtimePath = attribute.ArgumentList.Arguments[1]
                .Expression.ToString().Trim('"');

            string fullScanPath = Path.Combine(projectDir, scanPath);

            if (!Directory.Exists(fullScanPath))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "RL0002",
                        "Resources folder not found",
                        "ResourceLoader could not find the folder '{0}'",
                        "ResourceLoader",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None,
                    fullScanPath));
                return;
            }

            string[] files = Directory.GetFiles(fullScanPath);
            string className = classDecl.Identifier.Text;
            string namespaceName = GetNamespace(classDecl);

            // Just emit the file list as comments for now
            string fileList = string.Join("\n", files.Select(f => $"// {Path.GetFileName(f)}"));

            string source = $$"""
            // <auto-generated/>
            namespace {{namespaceName}};

            partial class {{className}}
            {
            {{fileList}}
            }
            """;

            ctx.AddSource($"{className}.g.cs", source);
        }

        private static string GetNamespace(ClassDeclarationSyntax classDecl)
        {
            SyntaxNode? parent = classDecl.Parent;
            while (parent is not null)
            {
                if (parent is NamespaceDeclarationSyntax ns)
                    return ns.Name.ToString();
                if (parent is FileScopedNamespaceDeclarationSyntax fns)
                    return fns.Name.ToString();
                parent = parent.Parent;
            }
            return "global";
        }
    }
}
